name: Deployment pipeline

env:
  SKIP: ${{ contains(join(github.event.commits.*.message, ', '), '#skip') }}
  RENDER_URL: https://part11-bloglist.onrender.com/

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4.0.4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
        run: npm test -- --verbose

      - name: E2E test (Playwright)
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
        run: |
          npm run start:test &
          npm run dev:frontend &
          sleep 5
          npx playwright install --with-deps
          npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5

  production_deployment:
    if: ${{ github.event_name == 'push' && !github.env.SKIP }}
    needs: [simple_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Render
        run: |
          echo "Deploying.."
          curl "https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}"

      - name: Success
        if: ${{ success() }}
        uses: stegzilla/discord-notify@v4
        with:
          title: A new version of Bloglist deployed
          colour: '#008000'
          message: to ${{ env.RENDER_URL }} by ${{ github.repository_owner }}
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Failure
        if: ${{ failure() }}
        uses: stegzilla/discord-notify@v4
        with:
          title: Build failed
          colour: '#FF0000'
          message: |
            ${{ github.event.head_commit.url }} by ${{ github.event.head_commit.author.username }} broke the build
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    if: ${{ github.event_name == 'push' && !github.env.SKIP }}
    needs: [production_deployment]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
